### ISSUE TITLE
Module is not idempotent when creating a new host

### ISSUE THREAD

**Issue by remkolodder** [dell/ansible-powermax#13]
We are currently deploying our PowerMax setup via Ansible and we notice that when creating a new host, the code doesn't appear to be idempotent.

See attached image;

![powermax_new_host_github](https://user-images.githubusercontent.com/695440/154956891-618464a4-897d-4866-b81d-ce57b3a1d171.jpg)

The following code is being used to deploy that ( a bit sanitized);

```
- name: "Create PowerMax host for {{ host }}"
dellemc.powermax.dellemc_powermax_host:
unispherehost: "{{ host }}"
universion: "{{ version }}"
verifycert: "{{ verifycert }}"
serial_no: "{{ serial }}"
user: "{{ username }}"
password: "{{ password }}"
host_name: "{{ host_name"
host_type: "default"
state: "present"
initiator_state: "present-in-host"
initiators: "{{ initiators }}"
```

**Comment by rawstorage** [comment]
Hi, the error doesn't appear to be one with idempotency but that the initiator is already in a host.  Have you verified that the initiator is not part of a host with a different name.?

**Comment by rawstorage** [comment]
![run1](https://user-images.githubusercontent.com/25058109/154983976-bde150a1-e226-40ee-8393-e7867202cc7e.jpg)
![run2](https://user-images.githubusercontent.com/25058109/154983998-c540e930-f263-4e20-b742-542e224e320e.jpg)
![error](https://user-images.githubusercontent.com/25058109/154984178-dbe3137b-1ed1-4e16-a4cb-8b9e537dce9a.jpg)

I'm able to reproduce this issue easily but it's not an idempotency issue, the error is due to initiator being in another host.  See images.

**Comment by rawstorage** [comment]
Hi @remkolodder, can you confirm that this was your issue and close the issue?

**Comment by remkolodder** [comment]
Hi Paul,

I will be checking this today. Cannot confirm this yet.

**Comment by remkolodder** [comment]
Hi Paul,

We figured out the issues, we are re-using existing machines with a different name in the current powermax setup. they are prefixed with a prefix, and when redeploying such a machine we expected the hosts part to rename the host(s).

That doesn't happen so we work around it by sniffing the log message, if the machine is already there, we do a different task and rename it.

That looks like this:

```
- name: "Create PowerMax host"
  when: (host.split('.')[0]) not in powermax_host_facts.Hosts
  dellemc.powermax.dellemc_powermax_host:
    unispherehost: "{{ host }}"
    universion: "{{ version }}"
    verifycert: "{{ verifycert }}"
    serial_no: "{{ serial }}"
    user: "{{ username }}"
    password: "{{ password }}"
    host_name: "{{ host.split('.')[0] }}"
    host_type: "default"
    state: "present"
    initiator_state: "present-in-host"
    initiators: "{{ initiators }}"
  register: host_add
  failed_when: >
    (host_add.msg is defined) and
    'is already part of a host' not in host_add.msg

- name: Rename host
  when: >
    (host_add.msg is defined) and
    'is already part of a host' in host_add.msg
  dellemc.powermax.dellemc_powermax_host:
    unispherehost: "{{ host }}"
    universion: "{{ version }}"
    verifycert: "{{ verifycert }}"
    serial_no: "{{ serial }}"
    user: "{{ username }}"
    password: "{{ password }}"
    host_name: "ig_{{ (host.split('.')[0] | replace('-', '_')) }}"
    new_name: "{{ host.split('.')[0] }}"
    state: "present"
```

Thanks for your efforts, it would be great when we can auto rename something but we can work around it like this as well :)
