### ISSUE TITLE
[QUESTION]: how to get details (IG/SG/PG) about specific MV?

### ISSUE THREAD

**Issue by 212850a** [dell/ansible-powermax#42]
We are trying to get details about specific masking view - what initiator group, storage group and port group it contains, but looks like such functionality is not available in current version of ansible-powermax. Isn't it?

We can get MV based on initiator group name (with a help of host_or_host_group_name filter), but how to know what storage group (SG) and port group (PG) is part of the same MV?

**Comment by 212850a** [comment]
Just found the answer by myself - if dellemc.powermax.maskingview module used without portgroup_name, hostgroup_name, sg_name values and has state: "present" it just returns details about what components (IG/SG/PG) masking view contains: 
```
- name: Show MV details
  dellemc.powermax.maskingview:
    unispherehost: "{{unispherehost}}"
    universion: "{{universion}}"
    verifycert: "{{verifycert}}"
    user: "{{user}}"
    password: "{{password}}"
    serial_no: "{{serial_no}}"
    mv_name: "{{mv_name}}"
    state: "present"
register: info
```
