### ISSUE TITLE
[BUG]: requirements.txt Does Not Limit (breaking EE dependency auto detection)

### ISSUE THREAD

**Issue by timway** [dell/ansible-powermax#66]
**Describe the bug**

The `ansible-builder` tool introspects collections and will install Python dependencies automatically. The `requirements.txt` in this collection isn't constrained so when a version lands on PyPi that is newer than what the collection supports the `ansible-builder` tool installs it and users fail to create an EE easily with an appropriate version of the Python module.

**To Reproduce**

1. Create an `execution-environment.yml` like so:

```yml
---
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install --upgrade pip

dependencies:
  galaxy: |-
    collections:
      - name: dellemc.powermax
        version: 3.1.0

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:1.0.0-887

options:
  package_manager_path: /usr/bin/microdnf

version: 3
```

2. Build the EE with `ansible-builder --tag forums-40293:v3 --verbosity 3`
3. Try to use the EE against a Dell PowerMax

**Expected behavior**

That `ansible-builder` dependency introspection works.

**Additional context**

**Workaround**

Constrain the Python version with the following added to the `execution-environment.yml`

```yml
---
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install --upgrade pip

dependencies:
  galaxy: |-
    collections:
      - name: dellemc.powermax
        version: 3.1.0
  python:
    - PyU4V <= 10.1.0.2

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:1.0.0-887

options:
  package_manager_path: /usr/bin/microdnf

version: 3
```
