### ISSUE TITLE
[BUG]: get_size_in_gb return wrong type

### ISSUE THREAD

**Issue by SerDroide** [dell/ansible-powermax#69]
**Describe the bug**
get_size_in_gb() function return decimal type that is not "compatible" with expand_volume_helper() logic

**To Reproduce**

Execute twice:

```yaml
- name: Create/expand a volume
  dellemc.powermax.volume:
    unispherehost: "{{ unisphere_host }}"
    port: "{{ unisphere_port }}"
    user: "{{ unisphere_username }}"
    password: "{{ unisphere_password }}"
    universion: "{{ unisphere_universion }}"
    verifycert: "{{ unisphere_verifycert }}"
    serial_no: "{{ powermax_serial_no }}"
    state: present
    vol_name: test
    size: 135
    cap_unit: MB
```

to hit this error also if the volume size is the same: https://github.com/dell/ansible-powermax/blob/main/plugins/modules/volume.py#L604

**Expected behavior**
No error raised

**Screenshots**

**Logs**

`fatal: [test_host_1_volume_5]: FAILED! => {"changed": false, "msg": "Current volume size 0.13 GB is greater than 0.13 GB specified."}`

**System Information (please complete the following information):**
 - collection delemc.powermax 3.1.1

 ```
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/home/automation/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /workspace/src/powermax/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.11 (main, Dec 12 2024, 16:28:23) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

**FIX
return a float

https://github.com/dell/ansible-powermax/blob/main/plugins/module_utils/storage/dell/utils.py#L318-L322

```python
def get_size_in_gb(size, cap_units):
    size_in_bytes = get_size_bytes(size, cap_units)
    size = Decimal(size_in_bytes / GB_IN_BYTES)
    size_in_gb = round(size, 2)
    return float(size_in_gb)
```
